### ISSUE TITLE
Bug with $MailboxStatsReport

### ISSUE THREAD

**Issue by ronwojnar1** [smcavinue/Tenant-Migration-Assessment-V2#2]
Lines 407 and 408 are exporting mailbox statistics via MGReporting, and importing the results as $MailboxStatsReport.

Later, starting at line 637, the script appears to be matching the data between $MailboxStatsReport and $users via $user via $user.id. and $user.userprincipalname. Unfortunately, $MailboxStatsReport contains the MGGraph numerical representation of the user object, while $user.id doesn't correlate to any value in $MailboxStatsReport, and $user.userprincipalname is the plain text representation of the UPN (you@somedomain.com).

**Comment by smcavinue** [comment]
I believe your issue is related to concealed names in reports which needs to be disabled before running the script as mentioned here: https://practical365.com/office-365-migration-plan-assessment/

**Comment by ghost** [comment]
And that makes perfect sense. You might wish to add that caveat to https://practical365.com/microsoft-365-tenant-to-tenant-migration-assessment-version-2/

**Comment by smcavinue** [comment]
Closing as query is answered. ReadMe will reflect all prerequisites also going forward
